<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f8d91d68-3e3a-4258-979e-e20e9191dd24</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolymarketLab.DataCollection.Infrastructure\PolymarketLab.DataCollection.Infrastructure.csproj" />
    <ProjectReference Include="..\PolymarketLab.DataCollection.Presentation\PolymarketLab.DataCollection.Presentation.csproj" />
    <ProjectReference Include="..\PolymarketLab.Markets.Infrastructure\PolymarketLab.Markets.Infrastructure.csproj" />
    <ProjectReference Include="..\PolymarketLab.Markets.Presentation\PolymarketLab.Markets.Presentation.csproj" />
  </ItemGroup>

</Project>
