// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolymarketLab.Markets.Infrastructure.Adapters.Postgres;

#nullable disable

namespace PolymarketLab.Markets.Infrastructure.Adapters.Postgres.Migrations
{
    [DbContext(typeof(MarketsDbContext))]
    [Migration("20260721122759_InitialMarkets")]
    partial class InitialMarkets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.Entity.MarketToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalTokenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_token_id");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("OutcomeIndex")
                        .HasColumnType("integer")
                        .HasColumnName("outcome_index");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "ExternalTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_market_tokens_market_id_external_token_id");

                    b.HasIndex("MarketId", "OutcomeIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_market_tokens_market_id_outcome_index");

                    b.ToTable("market_tokens", (string)null);
                });

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.MarketAggregate.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_id");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_market_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_condition_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_external_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_slug");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.Entity.MarketToken", b =>
                {
                    b.HasOne("PolymarketLab.Markets.Core.Domain.Models.Market.MarketAggregate.Market", null)
                        .WithMany("Tokens")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.MarketAggregate.Market", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
