// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolymarketLab.Markets.Infrastructure.Adapters.Postgres;

#nullable disable

namespace PolymarketLab.Markets.Infrastructure.Adapters.Postgres.Migrations
{
    [DbContext(typeof(MarketsDbContext))]
    [Migration("20260827075147_PersistEventIdentityAndSchedule")]
    partial class PersistEventIdentityAndSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.Entity.MarketToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalTokenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_token_id");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("OutcomeIndex")
                        .HasColumnType("integer")
                        .HasColumnName("outcome_index");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_market_tokens_external_token_id");

                    b.HasIndex("MarketId", "ExternalTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_market_tokens_market_id_external_token_id");

                    b.HasIndex("MarketId", "OutcomeIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_market_tokens_market_id_outcome_index");

                    b.ToTable("market_tokens", (string)null);
                });

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.MarketAggregate.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_id");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTimeOffset>("EventEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_ends_at");

                    b.Property<string>("EventSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_slug");

                    b.Property<DateTimeOffset>("EventStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_starts_at");

                    b.Property<DateTimeOffset?>("ExternalClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("external_closed_at");

                    b.Property<DateTimeOffset?>("ExternalCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("external_created_at");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_event_id");

                    b.Property<string>("ExternalMarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_market_id");

                    b.Property<DateTimeOffset?>("GammaStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gamma_start_date");

                    b.Property<string>("MarketSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_slug");

                    b.Property<DateTimeOffset?>("OrdersOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orders_opened_at");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTimeOffset>("ScheduleRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("schedule_refreshed_at");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_condition_id");

                    b.HasIndex("EventSlug")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_event_slug");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_external_event_id");

                    b.HasIndex("ExternalMarketId")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_external_market_id");

                    b.HasIndex("MarketSlug")
                        .IsUnique()
                        .HasDatabaseName("ux_markets_market_slug");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.Entity.MarketToken", b =>
                {
                    b.HasOne("PolymarketLab.Markets.Core.Domain.Models.Market.MarketAggregate.Market", null)
                        .WithMany("Tokens")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.Markets.Core.Domain.Models.Market.MarketAggregate.Market", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
