// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres;

#nullable disable

namespace PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Migrations
{
    [DbContext(typeof(DataCollectionDbContext))]
    [Migration("20260904101710_PersistCollectorTokenReadiness")]
    partial class PersistCollectorTokenReadiness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AwaitingNormalizationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awaiting_normalization_at");

                    b.Property<string>("ConditionId")
                        .HasColumnType("text")
                        .HasColumnName("condition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EventEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_ends_at");

                    b.Property<string>("EventSlug")
                        .HasColumnType("text")
                        .HasColumnName("event_slug");

                    b.Property<DateTimeOffset?>("EventStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_starts_at");

                    b.Property<short>("ExclusiveSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("exclusive_slot");

                    b.Property<string>("ExternalEventId")
                        .HasColumnType("text")
                        .HasColumnName("external_event_id");

                    b.Property<string>("ExternalMarketId")
                        .HasColumnType("text")
                        .HasColumnName("external_market_id");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_message");

                    b.Property<DateTimeOffset?>("InvalidatingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidating_at");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("MarketSlug")
                        .HasColumnType("text")
                        .HasColumnName("market_slug");

                    b.Property<int?>("Phase")
                        .HasColumnType("integer")
                        .HasColumnName("phase");

                    b.Property<int?>("ProjectionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("projection_version");

                    b.Property<DateTimeOffset?>("ResolutionConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_confirmed_at");

                    b.Property<long?>("ResolutionConnectionEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("resolution_connection_epoch");

                    b.Property<DateTimeOffset?>("ResolutionSignaledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_signaled_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("StopReason")
                        .HasColumnType("integer")
                        .HasColumnName("stop_reason");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.Property<DateTimeOffset?>("SubscriptionReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_ready_at");

                    b.Property<string>("WinningOutcome")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("winning_outcome");

                    b.Property<string>("WinningTokenId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("winning_token_id");

                    b.HasKey("Id");

                    b.HasIndex("ExclusiveSlot")
                        .IsUnique()
                        .HasDatabaseName("ux_collector_sessions_exclusive_slot")
                        .HasFilter("\"status\" IN (0, 1, 2, 6, 7)");

                    b.ToTable("collector_sessions", "data_collection", t =>
                        {
                            t.HasCheckConstraint("ck_collector_sessions_exclusive_slot", "\"exclusive_slot\" = 1");
                        });
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSessionToken", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("OutcomeIndex")
                        .HasColumnType("integer")
                        .HasColumnName("outcome_index");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_id");

                    b.HasKey("SessionId", "OutcomeIndex");

                    b.HasIndex("SessionId", "TokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_collector_session_tokens_session_token");

                    b.ToTable("collector_session_tokens", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BestBidAskEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<decimal>("BestAsk")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("best_ask");

                    b.Property<decimal>("BestBid")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("best_bid");

                    b.Property<decimal>("Spread")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("spread");

                    b.HasKey("EventId");

                    b.ToTable("best_bid_asks", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BookLevelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<int>("LevelIndex")
                        .HasColumnType("integer")
                        .HasColumnName("level_index");

                    b.Property<decimal>("Price")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("price");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<decimal>("Size")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Side", "LevelIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_book_levels_event_side_level_index");

                    b.ToTable("book_levels", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BookSnapshotEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<decimal?>("LastTradePrice")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("last_trade_price");

                    b.Property<decimal?>("TickSize")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("tick_size");

                    b.HasKey("EventId");

                    b.ToTable("book_snapshots", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorDatasetCleanupAuditRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("DeletedNormalizationCount")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_normalization_count");

                    b.Property<long>("DeletedNormalizedEventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_normalized_event_count");

                    b.Property<long>("DeletedRawMessageCount")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_raw_message_count");

                    b.HasKey("SessionId");

                    b.ToTable("collector_dataset_cleanup_audits", "data_collection", t =>
                        {
                            t.HasCheckConstraint("ck_collector_dataset_cleanup_audits_counts_nonnegative", "deleted_raw_message_count >= 0 AND deleted_normalization_count >= 0 AND deleted_normalized_event_count >= 0");
                        });
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorSessionProgressRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long>("CurrentConnectionEpoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("current_connection_epoch");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<long>("MessagesEnqueued")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("messages_enqueued");

                    b.Property<long>("MessagesPersisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("messages_persisted");

                    b.Property<long>("MessagesReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("messages_received");

                    b.Property<long>("ReconnectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("reconnect_count");

                    b.HasKey("SessionId");

                    b.ToTable("collector_session_progress", "data_collection", t =>
                        {
                            t.HasCheckConstraint("ck_collector_session_progress_counters_nonnegative", "messages_received >= 0 AND messages_enqueued >= 0 AND messages_persisted >= 0");

                            t.HasCheckConstraint("ck_collector_session_progress_epoch_nonnegative", "current_connection_epoch >= 0");

                            t.HasCheckConstraint("ck_collector_session_progress_reconnect_count_nonnegative", "reconnect_count >= 0");
                        });
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorTokenReadinessRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long>("ConnectionEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_epoch");

                    b.Property<string>("TokenId")
                        .HasColumnType("text")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset>("InitialBookEnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initial_book_enqueued_at");

                    b.HasKey("SessionId", "ConnectionEpoch", "TokenId");

                    b.ToTable("collector_token_readiness", "data_collection", t =>
                        {
                            t.HasCheckConstraint("ck_collector_token_readiness_epoch_positive", "connection_epoch > 0");
                        });
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.LastTradePriceEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<decimal?>("FeeRateBps")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("fee_rate_bps");

                    b.Property<decimal>("Price")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("price");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<decimal?>("Size")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("size");

                    b.Property<string>("TransactionHash")
                        .HasColumnType("text")
                        .HasColumnName("transaction_hash");

                    b.HasKey("EventId");

                    b.ToTable("last_trade_price", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.MarketResolutionAssetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_id");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("integer")
                        .HasColumnName("item_index");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "ItemIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_market_resolution_assets_event_id_item_index");

                    b.ToTable("market_resolution_assets", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.MarketResolutionEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("ExternalMarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_market_id");

                    b.Property<string>("WinningAssetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("winning_asset_id");

                    b.Property<string>("WinningOutcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("winning_outcome");

                    b.HasKey("EventId");

                    b.ToTable("market_resolutions", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NewMarketAssetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_id");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("integer")
                        .HasColumnName("item_index");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "ItemIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_new_market_assets_event_id_item_index");

                    b.ToTable("new_market_assets", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NewMarketEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventMessageDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_message_description");

                    b.Property<string>("EventMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_message_id");

                    b.Property<string>("EventMessageSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_message_slug");

                    b.Property<string>("EventMessageTicker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_message_ticker");

                    b.Property<string>("EventMessageTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_message_title");

                    b.Property<string>("ExternalMarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_market_id");

                    b.Property<decimal>("FeeScheduleExponent")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("fee_schedule_exponent");

                    b.Property<decimal>("FeeScheduleRate")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("fee_schedule_rate");

                    b.Property<decimal>("FeeScheduleRebateRate")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("fee_schedule_rebate_rate");

                    b.Property<bool>("FeeScheduleTakerOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("fee_schedule_taker_only");

                    b.Property<bool>("FeesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("fees_enabled");

                    b.Property<string>("GameStartTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_start_time");

                    b.Property<string>("GroupItemTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_item_title");

                    b.Property<decimal?>("Line")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("line");

                    b.Property<decimal>("OrderPriceMinTickSize")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("order_price_min_tick_size");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SportsMarketType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sports_market_type");

                    b.Property<decimal>("TakerBaseFee")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("taker_base_fee");

                    b.HasKey("EventId");

                    b.ToTable("new_markets", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetId")
                        .HasColumnType("text")
                        .HasColumnName("asset_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("MarketConditionId")
                        .HasColumnType("text")
                        .HasColumnName("market_condition_id");

                    b.Property<DateTimeOffset>("NormalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("normalized_at");

                    b.Property<int>("NormalizerVersion")
                        .HasColumnType("integer")
                        .HasColumnName("normalizer_version");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("projection_version");

                    b.Property<int>("RawItemIndex")
                        .HasColumnType("integer")
                        .HasColumnName("raw_item_index");

                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long?>("SourceTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("source_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ProjectionVersion", "EventType", "RawMessageId")
                        .HasDatabaseName("ix_normalized_events_projection_event_raw_message");

                    b.HasIndex("RawMessageId", "RawItemIndex", "ProjectionVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_normalized_events_raw_message_item_projection");

                    b.ToTable("normalized_events", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.PriceChangeItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_id");

                    b.Property<decimal?>("BestAsk")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("best_ask");

                    b.Property<decimal?>("BestBid")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("best_bid");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("integer")
                        .HasColumnName("item_index");

                    b.Property<decimal>("Price")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("price");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<decimal>("Size")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("size");

                    b.Property<long?>("SourceTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("source_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "SourceTimestamp")
                        .HasDatabaseName("ix_price_change_asset_id_source_timestamp");

                    b.HasIndex("EventId", "ItemIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_price_change_event_id_item_index");

                    b.ToTable("price_change", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.RawMarketMessageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConnectionEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_epoch");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Id")
                        .HasDatabaseName("ix_raw_market_messages_session_id");

                    b.HasIndex("SessionId", "ReceivedAt", "Id")
                        .HasDatabaseName("ix_raw_market_messages_session_received_id");

                    b.ToTable("raw_market_messages", "data_collection", t =>
                        {
                            t.HasCheckConstraint("ck_raw_market_messages_connection_epoch_positive", "connection_epoch > 0");
                        });
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.RawMessageNormalizationRecord", b =>
                {
                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("projection_version");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorField")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_field");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("RawMessageId", "ProjectionVersion");

                    b.HasIndex("ProjectionVersion", "Status", "RawMessageId")
                        .HasDatabaseName("ix_raw_message_normalizations_projection_status_raw_message_id");

                    b.ToTable("raw_message_normalizations", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AcceptingOrders")
                        .HasColumnType("boolean")
                        .HasColumnName("accepting_orders");

                    b.Property<bool?>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<string>("ConditionId")
                        .HasColumnType("text")
                        .HasColumnName("condition_id");

                    b.Property<long?>("ConnectionEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_epoch");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("EventSlug")
                        .HasColumnType("text")
                        .HasColumnName("event_slug");

                    b.Property<DateTimeOffset?>("ExternalClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("external_closed_at");

                    b.Property<string>("ExternalEventId")
                        .HasColumnType("text")
                        .HasColumnName("external_event_id");

                    b.Property<string>("ExternalMarketId")
                        .HasColumnType("text")
                        .HasColumnName("external_market_id");

                    b.Property<string>("MarketSlug")
                        .HasColumnType("text")
                        .HasColumnName("market_slug");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int?>("RawItemIndex")
                        .HasColumnType("integer")
                        .HasColumnName("raw_item_index");

                    b.Property<long?>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UmaResolutionStatus")
                        .HasColumnType("text")
                        .HasColumnName("uma_resolution_status");

                    b.Property<string>("WinnerOutcome")
                        .HasColumnType("text")
                        .HasColumnName("winner_outcome");

                    b.Property<string>("WinnerTokenId")
                        .HasColumnType("text")
                        .HasColumnName("winner_token_id");

                    b.HasKey("Id");

                    b.HasIndex("RawMessageId", "RawItemIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_resolution_observations_ws_raw_item")
                        .HasFilter("raw_message_id IS NOT NULL");

                    b.HasIndex("SessionId", "ObservedAt", "Id")
                        .HasDatabaseName("ix_resolution_observations_session_observed_id");

                    b.ToTable("resolution_observations", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationOutcomeEntity", b =>
                {
                    b.Property<long>("ObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("observation_id");

                    b.Property<int>("OutcomeIndex")
                        .HasColumnType("integer")
                        .HasColumnName("outcome_index");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_winner");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<decimal?>("Price")
                        .HasPrecision(29, 18)
                        .HasColumnType("numeric(29,18)")
                        .HasColumnName("price");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_id");

                    b.HasKey("ObservationId", "OutcomeIndex");

                    b.ToTable("resolution_observation_outcomes", "data_collection", t =>
                        {
                            t.HasCheckConstraint("ck_resolution_observation_outcomes_index_nonnegative", "outcome_index >= 0");
                        });
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionStateEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<long?>("ConfirmingObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("confirming_observation_id");

                    b.Property<DateTimeOffset?>("LastPollingCycleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polling_cycle_at");

                    b.Property<long>("LastScannedRawMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_scanned_raw_message_id");

                    b.Property<long?>("PrimaryObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("primary_observation_id");

                    b.HasKey("SessionId");

                    b.HasIndex("ConfirmingObservationId");

                    b.HasIndex("PrimaryObservationId");

                    b.ToTable("resolution_states", "data_collection", t =>
                        {
                            t.HasCheckConstraint("ck_resolution_states_cursor_nonnegative", "last_scanned_raw_message_id >= 0");
                        });
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.TickSizeChangeEntity", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<decimal>("NewTickSize")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("new_tick_size");

                    b.Property<decimal>("OldTickSize")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)")
                        .HasColumnName("old_tick_size");

                    b.HasKey("EventId");

                    b.ToTable("tick_size_changes", "data_collection");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSessionToken", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", null)
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BestBidAskEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BestBidAskEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BookLevelEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BookSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BookSnapshotEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.BookSnapshotEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorDatasetCleanupAuditRecord", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorDatasetCleanupAuditRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorSessionProgressRecord", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorSessionProgressRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.CollectorTokenReadinessRecord", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.LastTradePriceEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.LastTradePriceEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.MarketResolutionAssetEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.MarketResolutionEntity", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.MarketResolutionEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.MarketResolutionEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NewMarketAssetEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NewMarketEntity", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NewMarketEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NewMarketEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.RawMarketMessageRecord", null)
                        .WithMany()
                        .HasForeignKey("RawMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.PriceChangeItemEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.RawMarketMessageRecord", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.RawMessageNormalizationRecord", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.RawMarketMessageRecord", null)
                        .WithMany()
                        .HasForeignKey("RawMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationOutcomeEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationEntity", null)
                        .WithMany("Outcomes")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionStateEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfirmingObservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationEntity", null)
                        .WithMany()
                        .HasForeignKey("PrimaryObservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionStateEntity", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.TickSizeChangeEntity", b =>
                {
                    b.HasOne("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.NormalizedEventRecord", null)
                        .WithOne()
                        .HasForeignKey("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.TickSizeChangeEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Core.Domain.Models.CollectorSession.CollectorSession", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("PolymarketLab.DataCollection.Infrastructure.Adapters.Postgres.Models.ResolutionObservationEntity", b =>
                {
                    b.Navigation("Outcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
